#!/usr/bin/env python3
"""Generate the legacy entry point from the canonical service groups.

The source groups deliberately use only top-level services and volumes. Keep
their YAML text intact so generation needs no third-party YAML dependency.
"""
import argparse
from pathlib import Path
import re

DEPLOY = Path(__file__).resolve().parent.parent / 'jumpinchat-deploy'
GROUPS = ('app', 'media', 'data', 'email')


def generate():
    services = []
    volumes = []
    names = set()
    for group in GROUPS:
        source = (DEPLOY / f'compose.{group}.yml').read_text()
        section = None
        blocks = {'services': [], 'volumes': []}
        for line in source.splitlines():
            if line and not line.startswith((' ', '#')):
                section = line.rstrip(':')
                if section not in blocks:
                    raise ValueError(f'Unsupported top-level field in {group}: {section}')
                continue
            if section:
                blocks[section].append(line)
        for name in re.findall(r'^  ([\w-]+):', '\n'.join(blocks['services']), re.M):
            if name in names:
                raise ValueError(f'Duplicate service: {name}')
            names.add(name)
        services.append(f'  # {group} services\n' + '\n'.join(blocks['services']).strip('\n'))
        if blocks['volumes']:
            volumes.append('\n'.join(blocks['volumes']).strip('\n'))
    return ('# Generated by scripts/generate-compose.py; edit compose.{app,media,data,email}.yml.\n'
            '# Standalone entry point for Compose implementations without include support.\n\n'
            'services:\n' + '\n\n'.join(services) + '\n\nvolumes:\n'
            + '\n'.join(volumes) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = DEPLOY / 'docker-compose.yml'
    expected = generate()
    if args.check:
        if target.read_text() != expected:
            parser.exit(1, 'Compose definitions differ; run python3 scripts/generate-compose.py\n')
        print('Generated Compose definition is current')
    else:
        target.write_text(expected)
